### PR TITLE
Animals part 1

### PR DESCRIPTION
**Pull request by TheShadowOfHassen**
I decided to split the animals to multiple PRs so everyone stays sane.

There are crocodiles, chickens, sheep and camels as well as a fix for the fish

### CODE REVIEW

**Review by indoptogopt — CHANGES_REQUESTED** [review]

**Comment by indoptogopt** [comment]
Do you know the story about Themistocles and the two fighting chickens? That would be a cool reference.

**Comment by TheShadowOfHassen** [comment]
I do not know the story about the fighting chickens. Tell it to me and I'll put it in! Please!

**Comment by indoptogopt** [comment]
I couldn't find the original source of the chicken story. There's no proof, it seems like it's just a tale. I don't know where it comes from. But it's a cool tale.

**Comment by TheShadowOfHassen** [comment]
That's fine. I found it in several places in articles about chickens, but not in Herodotus or Plutarch.  is there anything else that needs changed? If not, I'll merge.

**Comment by indoptogopt** [comment]
You can merge it.

**Pull request merged**
