### PR TITLE
Spartan Heroes

### PR DESCRIPTION
**Pull request by indoptogopt**

### CODE REVIEW

**Review by TheShadowOfHassen — CHANGES_REQUESTED** [review]
You need a comma before independence in the last paragraph of Agus's  It's two independent clauses joined by a conjunction.

**Review by TheShadowOfHassen — CHANGES_REQUESTED** [review]
Could you put these in the spartan markdown folder? This might also be something I decided after you started work, but It'd be easier on ourselves if we had just one for Sparta. 

Also, the link to Britannica was dead, however I found stuff about Agis the third at the Alexander the Great article: https://www.britannica.com/biography/Alexander-the-Great

**Comment by TheShadowOfHassen** [comment]
I set up some of the changes as suggestions which you just have to hit commit suggestion, and it'll automatically add it to your PR.

Once you fix the problems there, I'll merge it.

**Comment by TheShadowOfHassen** [comment]
Let me know when you're done fixing this, and I'll look over it again.

**Comment by indoptogopt** [comment]
But you didnt set up suggestions

**Comment by TheShadowOfHassen** [comment]
For some of them, I did. It says where I "Suggested a change." It should be above where you see these. It says Comment suggestion there too.

Some of the changes you need to make, I only put in comments (also above) Sorry.

**Comment by indoptogopt** [comment]
I don't see any suggestions

**Comment by indoptogopt** [comment]
But I fixed everything you requested

**Comment by TheShadowOfHassen** [comment]
Ok I'll merge it. (I'm new to Git so I'll see about the change requests.

 Do me a favor and look at my new pull request: #3

**Pull request merged**
