### PR TITLE
Spartan Soldiers

### PR DESCRIPTION
**Pull request by indoptogopt**
I added descriptions for all champions, infantry and cavalry units.

### CODE REVIEW

**Comment by TheShadowOfHassen** [comment]
It looks pretty good once the suggested changes are done.

(I did think i got the changes to appear this time.)

I confess I didn't triple check your history sources or do any deep dives myself, however the info seems to check out.

**Comment by TheShadowOfHassen** [comment]
However, I did have to resolve conflicts. That anything bad on our part, but I'll need to double-check the spartan source file once this is merged. I have a feeling it might not be formatted right.

**Comment by indoptogopt** [comment]
I don't see any suggested changes. Maybe they are still pending. If so you need to click on the green review changes button and then select the option request changes to finish your review.

**Comment by TheShadowOfHassen** [comment]
Oops. I did say I was new to Github didn't i?

They should be up now.

**Comment by TheShadowOfHassen** [comment]
Is there any other changes you want to make? If not I'll merge it.

**Comment by indoptogopt** [comment]
It's ready to be merged

**Review by TheShadowOfHassen — APPROVED** [review]

**Pull request merged**
