### PR TITLE
Sparta Market/ Merchants

### PR DESCRIPTION
**Pull request by TheShadowOfHassen**
I added description for the Spartan market and both kinds of merchants.

### CODE REVIEW

**Comment by indoptogopt** [comment]
In the description of the market in the last sentence: did you mean "accept" ?

**Comment by indoptogopt** [comment]
And in the last sentence in the merchant ship text: did you mean "forget"?

**Comment by indoptogopt** [comment]
Also in the merchant ship description there need to be commas before and after "however"

**Review by indoptogopt — CHANGES_REQUESTED** [review]

**Comment by indoptogopt** [comment]
I wrote that two days ago but forgot to submit it🤦sorry

**Comment by TheShadowOfHassen** [comment]
That's OK. 

If there isn't anything else I'll merge this.

**Comment by indoptogopt** [comment]
It is ready to be merged

**Pull request merged**
